### PR TITLE
fix: show configuration on mobile

### PR DESCRIPTION
**Pull request by amareshsm**
**Description:**

Show configuration tab on mobile view.

Ref: #74

### CODE REVIEW

**Comment by nzakas** [comment]
The configuration section is visible now but tapping on it doesn’t toggle the section open or closed.

**Comment by amareshsm** [comment]
> The configuration section is visible now but tapping on it doesn’t toggle the section open or closed.
I will look into this.

**Comment by amareshsm** [comment]
The configuration tab is not available Boz In safari the order of execution of scripts differs. I am checking on this.

**Comment by snitin315** [comment]
How was this working earlier? Or is it not working from the start?

**Comment by amareshsm** [comment]
Previously It was working. I think [React 18 update](https://github.com/eslint/playground/commit/044df4563c21f723fe333d3b4b940fc135bafb23)  is causing this issue.

The order of execution of the script differs in the safari.

Expected Behaviour:
```
 <script src="/play/assets/js/playground.js"></script> -- 1st (It should be completed before loading other script)
 <script src="/play/assets/js/css-vars-ponyfill@2.js"></script> - 2nd
 <script src="/play/assets/js/focus-visible.js"></script> - 3rd
 <script src="/play/assets/js/select.js"></script> - 4th
 <script src="/play/assets/js/themes.js"></script> - 5th (also we are checking dom contentloaded event)
 <script src="/play/assets/js/main.js"></script> - 6th
```

Current Behaviour:

Other scripts (theme.js, main.js, focus-visible.js, etc) are loaded before completing the execution playground.js script. So event listeners are not getting added. Theme toggle buttons are also not shown in the UI.


Maybe we can revert the react 18 changes or we have to load other scripts after completing the execution of the playground.js script.

Workaround:
```
<script>
    function addScript(attribute, callback) {
        var script = document.createElement('script');
        for (var attr in attribute) {
            script.setAttribute(attr, attribute[attr] ? attribute[attr] : null)
        }
        if (callback)
            script.onload = callback;
        document.body.insertAdjacentElement('beforeend', script);
    }
    addScript({
        src: "{{ '/assets/js/playground.js' | url }}"
    }, function () {
        var files = ["{{ '/assets/js/css-vars-ponyfill@2.js' | url }}", "{{ '/assets/js/focus-visible.js' | url }}",
            "{{ '/assets/js/select.js' | url }}", "{{ '/assets/js/main.js' | url }}", "{{ '/assets/js/themes.js' | url }}"];
        files.forEach((src) => {
            addScript({
                src
            });
        });
    });
</script>
```

P.S: Tried using `defer` but it doesn't seem to be solving the issue.

**Comment by snitin315** [comment]
In that case, can we try reverting the react v18 upgrade?

**Comment by harish-sethuraman** [comment]
Im quite confused Why'd we even want to have this code (configuration expander) in separate js file? We can do the same in react? inside the same component?

**Comment by snitin315** [comment]
@harish-sethuraman yes, we can do it in react.

**Comment by harish-sethuraman** [comment]
Shall I work on it?

**Comment by snitin315** [comment]
If that will fix this issue, I'm 👍 on it.

**Comment by amareshsm** [comment]
Closing this in favor of #87

**Pull request closed without merging**
