### PR TITLE
fix: dev server command

### PR DESCRIPTION
**Pull request by harish-sethuraman**
Seems like `npm start` is not the right command to start the dev server? so fixed it to `npm watch:eleventy`

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
watch:eleventy will not run webpack build.

**Comment by harish-sethuraman** [comment]
Ummm I used higher node version 17 so node-sass failed and `npm watch:eleventy` worked for me (although watch doesn't run). May be we can add engines in `package.json`?

**Comment by snitin315** [comment]
With which versions node-sass is compatible?

**Comment by harish-sethuraman** [comment]
The version we use is supported till 16 - https://github.com/sass/node-sass/releases/tag/v6.0.1 

Shall I add engines in this PR then? and remove that command change?

**Comment by snitin315** [comment]
Yes. Just add node 16 in engine.

**Comment by nzakas** [comment]
`npm start` works fine for me. What problem are you seeing?

**Comment by harish-sethuraman** [comment]
This was occurring with `node-sass` since we have migrated to `dart-sass` we can ignore this

**Pull request closed without merging**
