### PR TITLE
perf: use react v18

### PR DESCRIPTION
**Pull request by amareshsm**
Description:
1. Updated React to v18 to make use of new features like automatic batching, transitions, etc.
2. use React strict mode to catch bugs and highlight potential problems in development mode.

### CODE REVIEW

**Comment by snitin315** [comment]
Is codemirror compatible with react@18?

**Comment by nzakas** [comment]
We should get a deploy preview momentarily to test it out.

**Review by nzakas — APPROVED** [review]
LGTM. Would like @snitin315 to review.

**Review by snitin315 — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
